import type { Metadata } from "next";
import { Overlock_SC } from "next/font/google";
import "../styles/globals.css";

const overlock = Overlock_SC({
  weight: "400",
  variable: "--font-overlock",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Dev Journal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${overlock.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
